# Generated by Django 5.0.6 on 2024-06-04 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tagged_documents", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tagg",
            old_name="name",
            new_name="slug",
        ),
    ]
