# Generated by Django 5.0.6 on 2024-06-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tagged_documents", "0002_rename_name_tagg_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="tags",
            field=models.ManyToManyField(blank=True, to="tagged_documents.tagg"),
        ),
    ]
